# Site settings
title: aasdkl's blog!
email: hsuehchiahao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog for aasdkl.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://aasdkl.github.io"

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
weibo:  'tonyhsueh'
github: 'aasdkl'


# Comment
# disqus_shortname: discussion_shortname
youyan_id:2114211

useGoogle: false

# Google Analytics
google_analytics: tracking_ID

# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
